image: ubuntu:16.04

before_script:
  - apt-get -y update && apt-get -y upgrade && apt-get -y install bc build-essential zip curl libstdc++6      git wget python gcc clang libssl-dev repo rsync flex bison gcc-aarch64-linux-gnu
  - git config --global user.name "d4rklucif3r"
  - git config --global user.email "lucifer78908@gmail.com"
  - git config --global color.ui true
  - git clone https://github.com/akhilnarang/scripts && cd scripts && bash setup/android_build_env.sh && cd ..
  - cd /home
  - mkdir lucifer
  - cd lucifer
  - mkdir Android                 
  - cd Android
  - mkdir kernel
  - cd kernel
  - wget https://raw.githubusercontent.com/d4rk-lucif3r/LuciferKernel/NonOC/.circleci/build.sh
  
stages:
  - build


build:
  stage: build
  script: 
    - source build.sh
